version: '3'

services:
  db:
    image: postgres
    container_name: psql
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env/
    networks:
      - web

  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: django
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env/
    volumes:
      - .:/app-py17
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web

volumes:
  data:

  
networks:
  web:
    driver: bridge